[project]
name = "rag-lab-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
rag-lab-generator = "rag_lab_generator:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "pre-commit>=4.6.2",
    "pylint>=4.0.7",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.3",
]

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
]
