/**
 * Role:   Verifies the node details panel: description, grouped sources and chunk inspection.
 * Input:  A hand-built /api/graph/chunks payload rendered through <NodeSummary/>.
 * Output: Assertions on the description text, the corpus link of a lab, the lecture group
 *         without a link and the chunk handed to onInspect when a location is clicked.
 * Flow:   Renders the component inside a MemoryRouter (the lab title is a <Link/>), then
 *         checks the visible text and clicks a location; a second render without a description
 *         must show the hint naming the CLI command that generates one.
 */
import { fireEvent, render, screen } from '@testing-library/react'
import { MemoryRouter } from 'react-router'
import { describe, expect, it, vi } from 'vitest'

import type { NodeChunks } from '../../src/api/types'
import { NodeSummary } from '../../src/components/NodeSummary'

const PAYLOAD: NodeChunks = {
  node_id: 'concept:pipe',
  description: {
    text: 'A pipe is a one-way byte channel between related processes.',
    model: 'claude-opus-5',
    generated_at: '2026-09-22T12:00:00Z',
  },
  sources: [
    {
      document_id: 'sop2/l5',
      title: 'FIFO/pipe',
      kind: 'lab',
      course: 'sop2',
      lab_id: 'sop2/l5',
      slug: 'l5_fifo_pipe',
      locations: [{ chunk_id: 'c1', label: 'Task 1 - FIFO > Stage 3', kind: 'tutorial' }],
    },
    {
      document_id: 'sop2/lecture/pipes/POSIX-pipes',
      title: 'POSIX-pipes',
      kind: 'lecture_pdf',
      course: 'sop2',
      lab_id: null,
      slug: null,
      locations: [
        { chunk_id: 'c2', label: 'page 3', kind: 'lecture' },
        { chunk_id: 'c3', label: 'page 20', kind: 'lecture' },
      ],
    },
  ],
  chunks: [
    { id: 'c1', document_id: 'sop2/l5', lab_id: 'sop2/l5', kind: 'tutorial', section_id: 'stage-3', text: 'stage text' },
    { id: 'c2', document_id: 'sop2/lecture/pipes/POSIX-pipes', lab_id: null, kind: 'lecture', section_id: 'page-3', text: 'p3' },
    { id: 'c3', document_id: 'sop2/lecture/pipes/POSIX-pipes', lab_id: null, kind: 'lecture', section_id: 'page-20', text: 'p20' },
  ],
}

function renderSummary(data: NodeChunks, onInspect = vi.fn()) {
  render(
    <MemoryRouter>
      <NodeSummary data={data} onInspect={onInspect} />
    </MemoryRouter>,
  )
  return onInspect
}

describe('NodeSummary', () => {
  it('shows the description, links the lab and lists lecture pages', () => {
    renderSummary(PAYLOAD)
    expect(screen.getByText(/one-way byte channel/)).toBeInTheDocument()
    expect(screen.getByText('generated by claude-opus-5')).toBeInTheDocument()
    expect(screen.getByRole('link', { name: 'FIFO/pipe' })).toHaveAttribute(
      'href',
      '/corpus/sop2/l5_fifo_pipe',
    )
    expect(screen.queryByRole('link', { name: 'POSIX-pipes' })).toBeNull()
    expect(screen.getByText('POSIX-pipes')).toBeInTheDocument()
    expect(screen.getByText(/2 documents, 3 places/)).toBeInTheDocument()
  })

  it('hands the clicked location chunk to onInspect', () => {
    const onInspect = renderSummary(PAYLOAD)
    fireEvent.click(screen.getByRole('button', { name: 'page 20' }))
    expect(onInspect).toHaveBeenCalledWith(PAYLOAD.chunks[2])
  })

  it('tells how to generate a missing description', () => {
    renderSummary({ ...PAYLOAD, description: null })
    expect(screen.getByText(/rag-lab graph-describe/)).toBeInTheDocument()
  })
})
