/**
 * Role:   Details of the selected graph node: its generated description and grouped sources.
 * Input:  The /api/graph/chunks payload of one node and a callback opening a chunk inspector.
 * Output: A description paragraph, then one collapsible group per source document whose
 *         entries open the underlying chunk.
 * Flow:   Indexes the chunks by id, prints the description (or the hint to generate one),
 *         renders every source as a <details> block headed by the document title, linking labs
 *         to their corpus page, and hands the clicked location's chunk to onInspect.
 */
import { Link } from 'react-router'

import type { ChunkPreview, NodeChunks } from '../api/types'
import { Badge } from './ui'

export function NodeSummary({
  data,
  onInspect,
}: {
  data: NodeChunks
  onInspect: (chunk: ChunkPreview) => void
}) {
  const byId = new Map(data.chunks.map((chunk) => [chunk.id, chunk]))
  const total = data.sources.reduce((sum, source) => sum + source.locations.length, 0)
  return (
    <div className="space-y-3 text-xs">
      {data.description ? (
        <div>
          <p className="leading-relaxed text-slate-700 dark:text-slate-200">
            {data.description.text}
          </p>
          <p className="mt-1 text-[11px] text-slate-500">generated by {data.description.model}</p>
        </div>
      ) : (
        <p className="text-slate-500">
          No description yet. Run <code>rag-lab graph-describe</code> to generate one.
        </p>
      )}

      {data.sources.length === 0 ? (
        <p className="text-slate-500">This node has no attached sources.</p>
      ) : (
        <div>
          <p className="mb-1 font-semibold text-slate-500">
            Sources · {data.sources.length} documents, {total} places
          </p>
          <ul className="space-y-1.5">
            {data.sources.map((source) => (
              <li key={source.document_id}>
                <details className="rounded-lg border border-slate-200 p-2 dark:border-slate-800">
                  <summary className="flex cursor-pointer items-center gap-1.5">
                    <Badge tone="info">{source.kind}</Badge>
                    {source.slug ? (
                      <Link
                        to={`/corpus/${source.course}/${source.slug}`}
                        className="truncate font-medium text-indigo-600 hover:underline dark:text-indigo-400"
                      >
                        {source.title}
                      </Link>
                    ) : (
                      <span className="truncate font-medium">{source.title}</span>
                    )}
                    <span className="ml-auto text-[11px] text-slate-500">
                      {source.locations.length}
                    </span>
                  </summary>
                  <ul className="mt-2 space-y-0.5">
                    {source.locations.map((location) => {
                      const chunk = byId.get(location.chunk_id)
                      return (
                        <li key={location.chunk_id}>
                          <button
                            type="button"
                            disabled={!chunk}
                            onClick={() => chunk && onInspect(chunk)}
                            className="w-full rounded px-1.5 py-1 text-left hover:bg-slate-100 disabled:opacity-50 dark:hover:bg-slate-800"
                          >
                            {location.label}
                          </button>
                        </li>
                      )
                    })}
                  </ul>
                </details>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}
